### ISSUE TITLE
Error: subscript out of bounds when jma_collect()

### ISSUE THREAD

**Issue by kangjf1943** [uribo/jmastats#4]
I guess that is related to the data source (JMA website) though ... when I tried to find some the weather data of some block_no, it says "subscript out of bounds". Two examples are as follows. 
```
jma_collect(item = "daily", block_no = "0881", year = 2020, month = 1)
# Data from: https://www.data.jma.go.jp/obd/stats/etrn/view/daily_s1.php?prec_no=88&block_no=0881&year=2020&month=1&day=&view=Error in df[[6]] : subscript out of bounds
jma_collect(item = "daily", block_no = "1461", year = 2020, month = 1)
# Data from: https://www.data.jma.go.jp/obd/stats/etrn/view/daily_s1.php?prec_no=19&block_no=1461&year=2020&month=1&day=&view=Error in df[[6]] : subscript out of bounds
```
Of course, I can't access the links in the error message (it says "ページを表示することが出来ませんでした。ブラウザの「戻る」ボタンをクリックしてください。" 
My questions are: 
- I got the block_no from nearest_station(), so probably it is better to remove those block_no from nearest_station() function? 
- Can I find another alternative station in that case? For example, if the nearest station to my target location is the station with block_no = "1461", but that station doesn't have data (as shown above), how can I find an alternative station?

**Comment by kangjf1943** [comment]
Then, the error happens again, and I found it is still the block_no == "0881". The station doesn't have data at least between 1991 and 2023. 

```
for (i in 1991:2023) {
  print(i)
  tryCatch(
    jma_collect(item = "daily", block_no = "0881", year = i, month = 1), 
    error = function(e) NA, 
    finally = print("Subscript out of bounds")
  )
}
```

Do you know where I can find the location of the stations? For example, if I can find the location of block_no = "0881", then I can find another station near it, so that I can replace the data of block_no = "0881" by this alternative.

**Comment by uribo** [comment]
No, this is an error due to an incorrect URL specification on the package side.

Specifically, this was due to incorrect identification of station_type **a1** and **s1**.

Wrong: [https://www.data.jma.go.jp/obd/stats/etrn/view/**daily_s1**.php?prec_no=88&block_no=0881&year=2020&month=1&day=&view=
](https://www.data.jma.go.jp/obd/stats/etrn/view/daily_s1.php?prec_no=88&block_no=0881&year=2020&month=1&day=&view=)
Correct: [https://www.data.jma.go.jp/obd/stats/etrn/view/**daily_a1**.php?prec_no=88&block_no=0881&year=2020&month=1&day=&view=](https://www.data.jma.go.jp/obd/stats/etrn/view/daily_a1.php?prec_no=88&block_no=0881&year=2020&month=1&day=&view=)
